//! Differential parity (WP-4 step 3 / CHG-052): the Rust projection emitter's PositionSnapshot
//! arithmetic must reproduce the JVM `PositionProjectorDriver` oracle field-for-field for the same
//! fill sequence, and the negative oversell must be a VIOLATION on both sides.
//!
//! Cross-language mechanics: the oracle's output is pinned as a committed JSON fixture
//! (`tests/fixtures/positions_oracle.json`) generated by running the real Java
//! `PositionProjectorDriver` (via `DifferentialParityFixtureTest` in `code/common`). This test
//! rebuilds the identical scenario numerically, drives the Rust `PositionProjectorDriver`, and
//! asserts every projected snapshot equals the oracle's snapshot at the same step — including the
//! weighted-average arithmetic (integer, truncating) that must match Java `long` division exactly.

use nautilus_execution_service::projection::{FillEvent, PositionProjectorDriver, Side};

const NOW: i64 = 1000;
const POSITION_ID: &str = "pos-acc-1-1001-BUY-1";

fn fill(seq: i64, side: Side, qty: i64, price_paise: i64) -> FillEvent {
    FillEvent {
        position_id: POSITION_ID.to_string(),
        trade_context_id: "tc-1".to_string(),
        account_scope_id: "acc-1".to_string(),
        instrument_token: 1001,
        exchange: "CME".to_string(),
        symbol: "wti".to_string(),
        side,
        fill_qty: qty,
        fill_price_paise: price_paise,
        source_event_id: format!("evt-{seq}"),
        source_sequence: seq,
        event_time_ms: NOW,
    }
}

fn load_fixture() -> serde_json::Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/positions_oracle.json"
    );
    let raw = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("cannot read oracle fixture {path}: {e}"));
    serde_json::from_str(&raw).expect("oracle fixture must be valid JSON")
}

#[test]
fn rust_emitter_reproduces_java_oracle_positions_sequence() {
    let oracle = load_fixture();
    let position_id = oracle["position_id"].as_str().expect("position_id");
    assert_eq!(position_id, POSITION_ID);

    // Rebuild the Java scenario: BUY10@1000, BUY5@1100, SELL8@1050, SELL7@1060 on the SAME
    // resolved position id (both sides feed the explicit id — id minting is a separate concern).
    let steps: Vec<(i64, Side, i64, i64)> = vec![
        (1, Side::Buy, 10, 1000),
        (2, Side::Buy, 5, 1100),
        (3, Side::Sell, 8, 1050),
        (4, Side::Sell, 7, 1060),
    ];

    let mut driver = PositionProjectorDriver::new();
    let positive = oracle["positive"].as_array().expect("positive[]");
    assert_eq!(positive.len(), steps.len());

    for (idx, ((seq, side, qty, price), expected)) in steps.iter().zip(positive.iter()).enumerate()
    {
        let f = fill(*seq, *side, *qty, *price);
        let r = driver.feed_fill(&f, NOW);
        // Outcome must be APPLIED at every (valid) step, exactly like the oracle.
        assert_eq!(
            r.outcome,
            nautilus_execution_service::projection::FeedOutcome::Applied,
            "step {idx}: Rust outcome must be APPLIED"
        );
        let snapshot = r.snapshot.expect("applied snapshot");

        assert_eq!(
            snapshot.state.as_str(),
            expected["state"].as_str().unwrap(),
            "step {idx}: state"
        );
        assert_eq!(
            snapshot.open_quantity,
            expected["open"].as_i64().unwrap(),
            "step {idx}: open"
        );
        assert_eq!(
            snapshot.closed_quantity,
            expected["closed"].as_i64().unwrap(),
            "step {idx}: closed"
        );
        assert_eq!(
            snapshot.average_entry_paise,
            expected["avgEntry"].as_i64().unwrap(),
            "step {idx}: avgEntry"
        );
        assert_eq!(
            snapshot.average_exit_paise,
            expected["avgExit"].as_i64().unwrap(),
            "step {idx}: avgExit"
        );
        assert_eq!(
            snapshot.source_version,
            expected["sourceVersion"].as_i64().unwrap(),
            "step {idx}: sourceVersion"
        );
        assert_eq!(
            snapshot.source_event_id,
            expected["sourceEventId"].as_str().unwrap(),
            "step {idx}: sourceEventId"
        );
    }

    // Terminal anchor: closed position with open == closed == 15.
    let final_snap = driver.snapshot(POSITION_ID).expect("final snapshot");
    assert_eq!(
        (final_snap.open_quantity, final_snap.closed_quantity),
        (15, 15)
    );
    assert_eq!(final_snap.state.as_str(), "CLOSED");
}

#[test]
fn oversell_is_a_violation_on_rust_matching_java_oracle() {
    let oracle = load_fixture();
    assert_eq!(oracle["oversell_outcome"].as_str().unwrap(), "VIOLATION");
    assert!(
        oracle["oversell_reason_has_overshoots"].as_bool().unwrap(),
        "oversell fixture must record overshoot detail"
    );

    let mut driver = PositionProjectorDriver::new();
    let r1 = driver.feed_fill(&fill(1, Side::Buy, 10, 1000), NOW);
    assert_eq!(
        r1.outcome,
        nautilus_execution_service::projection::FeedOutcome::Applied
    );
    let oversell = driver.feed_fill(&fill(2, Side::Sell, 20, 900), NOW);
    assert_eq!(
        oversell.outcome,
        nautilus_execution_service::projection::FeedOutcome::Violation
    );
    assert!(
        oversell
            .reason
            .as_deref()
            .unwrap_or("")
            .contains("overshoots"),
        "Rust violation reason must carry the overshoot detail like the Java oracle"
    );
}
