package com.trading.ingestion.bridge;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Golden-corpus tests for {@link PayloadHashValidator}.
 *
 * <p>Consumes the same raw frames + Base64 raw_payload + SHA-256 payload_hash
 * pairs the Go bridge emits (testdata/golden/ under go-bridge). This is the
 * byte-for-byte decode contract between the Go bridge and the Java pipeline:
 * the validator must accept every golden packet and reject a tampered copy.
 *
 * <p>Golden files are generated by {@code go-bridge/cmd/gen-corpus} (build
 * tag-free) and committed — they are the authoritative decode fixture.
 */
@DisplayName("ING-UNIT-010b: golden-corpus payload hash validation")
class GoldenCorpusPayloadHashTest {

    /** Locate the go-bridge golden corpus — surefire cwd varies (module vs reactor root). */
    private static final Path GOLDEN_DIR = locateGoldenDir();

    private static Path locateGoldenDir() {
        Path[] candidates = {
            Path.of("go-bridge/testdata/golden"),         // module cwd (sibling go-bridge)
            Path.of("../../go-bridge/testdata/golden"),   // parent-of-parent fallback
            Path.of("02_services/01_ingestion/go-bridge/testdata/golden"), // reactor root
        };
        for (Path p : candidates) {
            if (Files.isDirectory(p)) {
                return p;
            }
        }
        throw new IllegalStateException(
                "golden corpus not found; cwd=" + Path.of("").toAbsolutePath()
                + " tried " + java.util.Arrays.toString(candidates));
    }

    private record Golden(String name, byte[] frame, String rawPayloadB64, String payloadHash) {}

    private static Golden loadGolden(String name) throws IOException {
        byte[] frame = Files.readAllBytes(GOLDEN_DIR.resolve(name + ".frame"));
        String goldenText = Files.readString(GOLDEN_DIR.resolve(name + ".golden")).trim();
        // The .golden files are JSON with raw_payload + payload_hash fields.
        String rawPayloadB64 = extractField(goldenText, "raw_payload");
        String payloadHash = extractField(goldenText, "payload_hash");
        return new Golden(name, frame, rawPayloadB64, payloadHash);
    }

    private static String extractField(String json, String field) {
        String key = "\"" + field + "\":\"";
        int start = json.indexOf(key);
        if (start < 0) {
            throw new IllegalStateException("golden missing field " + field + ": " + json);
        }
        start += key.length();
        int end = json.indexOf('"', start);
        return json.substring(start, end);
    }

    @Test
    @DisplayName("every golden packet validates and decodes to the exact frame bytes")
    void goldenPacketsValidate() throws IOException {
        // response is a wire-only fixture (subscription ack, never NDJSON);
        // only emitted tick frames carry raw_payload + payload_hash.
        for (String name : new String[] {"full-tick", "ltp-tick"}) {
            Golden g = loadGolden(name);
            assertEquals(PayloadHashValidator.Result.VALID,
                    PayloadHashValidator.validate(g.rawPayloadB64(), g.payloadHash()),
                    "golden " + g.name() + " must validate");
            assertArrayEquals(g.frame(),
                    PayloadHashValidator.decodeValid(g.rawPayloadB64(), g.payloadHash()),
                    "golden " + g.name() + " must decode to the exact frame bytes");
        }
    }

    @Test
    @DisplayName("tampering with a golden frame changes the hash and is rejected")
    void tamperedGoldenRejected() throws IOException {
        Golden g = loadGolden("full-tick");
        byte[] tampered = g.frame().clone();
        tampered[8] ^= 0x01; // flip one bit of the LTP field
        String tamperedB64 = Base64.getEncoder().encodeToString(tampered);
        assertEquals(PayloadHashValidator.Result.HASH_MISMATCH,
                PayloadHashValidator.validate(tamperedB64, g.payloadHash()),
                "tampered golden must be rejected");
    }

    @Test
    @DisplayName("golden raw_payload base64 decodes to the exact frame length")
    void goldenPayloadDecodesToFrameLength() throws IOException {
        for (String name : new String[] {"full-tick", "ltp-tick"}) {
            Golden g = loadGolden(name);
            byte[] decoded = Base64.getDecoder().decode(g.rawPayloadB64());
            assertEquals(g.frame().length, decoded.length,
                    "golden " + g.name() + " raw_payload must decode to frame length");
        }
    }
}
